apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: nginx-alert-rules
  namespace: kube-system
  labels:
    release: prometheus
spec:
  groups:
    - name: nginx.rules
      rules:
        - alert: NginxPodDown
          expr: absent(kube_pod_status_ready{namespace="default", pod=~"nginx-deployment-.*"})
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "Nginx Pod is down"
            description: "No ready pod found for Nginx deployment in the default namespace."

        - alert: HighCpuUsage
          expr: (sum(rate(container_cpu_usage_seconds_total{namespace="default", pod=~"nginx-deployment.*"}[5m])) * 100) > 80
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "High CPU usage on Nginx"
            description: "CPU usage on Nginx pods is above 80% for more than 2 minutes."

        - alert: HighMemoryUsage
          expr: (sum(container_memory_usage_bytes{namespace="default", pod=~"nginx-deployment.*"}) / sum(machine_memory_bytes)) * 100 > 80
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "High Memory usage on Nginx"
            description: "Memory usage on Nginx pods is above 80% for more than 2 minutes."
