apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: test-alert-rule
  namespace: kube-system
  labels:
    release: prometheus
spec:
  groups:
  - name: test.rules
    rules:
    - alert: AlwaysFiring
      expr: vector(1)
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "This is a test alert that always fires"
        description: "Use this alert to test email notification setup"
